name: Lint and Test
on:
  - push
  - pull_request
jobs:
  unit_tests:
    name: Lint and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rev:
          - nightly
          - v0.9.5
          - v0.10.0
        include:
          - os: ubuntu-latest
            install-rg: sudo apt-get update && sudo apt-get install -y ripgrep luarocks
          - os: macos-latest
            install-rg: brew update && brew install ripgrep luarocks
          - os: windows-latest
            install-rg: choco install ripgrep luarocks
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.rev }}
      - name: Prepare
        run: |
          ${{ matrix.install-rg }}
          rg --version
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ../plenary.nvim
          sudo luarocks install luacheck
      - name: Run tests
        run: |
          nvim --version
          make test
      - name: Run linter
        run: luacheck lua/
